# Build Environment
FROM node:19.0.0-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci --silent
# Have a .dockerignore file ignoring node_modules and build
COPY . ./
RUN npm run build
# Production
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

### CREAR LA IMAGEN LOCALMENTE
### docker build --tag nombre_imagen .

### CORRER LA IMAGEN
### docker run -p 3000:3000 nombre_imagen