FROM node:16.18.0
# create & set working directory
RUN mkdir -p /src
WORKDIR /src
# copy source files
COPY . /src
# install dependencies
RUN npm install
# start app
RUN npm run build
EXPOSE 3000
# start app
CMD ["npm", "start"]


### CREAR LA IMAGEN LOCALMENTE
### docker build --tag jhonathantocay/frontend-clasen .

### CORRER LA IMAGEN
### docker run -p 3000:3000 jhonathantocay/frontend-clasen

### SUBIR LA IMAGEN
### docker push jhonathantocay/frontend-clasen